name: mlops-example
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # container: node:latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      # - uses: iterative/setup-cml@v1
      # - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python FH_Analyse_savefile.py
          
          #cat metrics.txt >> report.md
          #cml-publish plot.png --md >> report.md
          #cml-send-comment report.md
