name: MLOps-offline_regression_testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          pip install --upgrade pip
          pip install -e .
          
          python mindaffectBCI/decoder/offline_regression_testing.py
          python csv2text.py
          
          echo "## OFFLINE REGRESSION TESTING" > report.md
          echo "\n## Kaggle" > report.md
          cat kaggle.txt >> report.md
          echo "\n## Plos one" > report.md
          cat plos_one.txt > report.md
          echo "\n## Lowlands" > report.md
          cat lowlands.txt > report.md
          
          cml-send-comment report.md
