name: MLOps-offline_regression_testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python mindaffectBCI/decoder/offline_regression_testing.py
          
          echo "## OFFLINE REGRESSION TESTING" > report.md
          echo "\n## Model Metrics" > report.md
          cat metrics.json >> report.md
          
          # echo "\n## Model Performance" >> report.md
          # echo "Model performance metrics are on the plot below." >> report.md
          
          # cml-publish mindaffectBCI_decoding_curve.png --md >> report.md
          
          cml-send-comment report.md
