name: MLOps-offline_regression_testing
on:
  push:
  issues:
    types: [created]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Installing prerequisites
          pip install -r requirements-pipeline.txt
          pip install --upgrade pip
          pip install --upgrade pip setuptools wheel
          pip install -e .
          
          # Programs to run
          python mindaffectBCI/decoder/offline_regression_testing.py
          python csv2text.py
          
          # Output
          echo "## OFFLINE REGRESSION TESTING" > report.md
          cat metrics.txt >> report.md
          
          cml-send-comment report.md
